#! /bin/bash -ex

mkdir -p target0 target1 target2
scalac -d target -nowarn macro.scala
scalac -cp target -d target1 -nowarn a.scala b.scala
scalac -cp target -d target2 -nowarn b.scala a.scala
function show() {
    javap -cp $1 -v $2 | egrep -v 'Classfile|checksum'
}
diff -u <(show target1 demo.a) <(show target2 demo.a)

