#! /bin/bash -ex

mkdir -p target1 target2
scalac -d target1 -nowarn -Xprint:all a.scala b.scala 2>&1 | egrep -v '\.scala' > target1/log
scalac -d target2 -nowarn -Xprint:all b.scala a.scala 2>&1 | egrep -v '\.scala' > target2/log
function show() {
    javap -cp $1 -v $2 | egrep -v 'Classfile|checksum'
}
diff -U10000 target1/log target2/log
diff -u <(show target1 demo.a) <(show target2 demo.a)

